<?php

/*
Plugin Name: My extended sitemap
Plugin URI: http://lloc.de/msls
Description: This small WordPress plugin shows how simple it is to extend a xml sitemap generated by BWP Google XML Sitemap 
Version: 0.9.6
Author: Dennis Ploetner 
Author URI: http://lloc.de/
*/

/*
Copyright 2012  Dennis Ploetner  (email : re@lloc.de)

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License, version 2, as 
published by the Free Software Foundation.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/

/**
 * Flush rewrite rules
 */
function mxs_flush_rules() {
    global $wp_rewrite;
    $wp_rewrite->flush_rules();
}
register_activation_hook( __FILE__, 'mxs_flush_rules' );
register_deactivation_hook( __FILE__, 'mxs_flush_rules' );

/**
 * Add 'specials' as module
 */
function mxs_add_modules() {
    global $bwp_gxs;
    $bwp_gxs->add_module( 'specials' );
}
add_action( 'bwp_gxs_modules_built', 'mxs_add_modules' );

/**
 * Add rule for specials.xml
 * @return array
 */
function mxs_add_rules() {
    return array( 'specials\.xml' => 'index.php?gxs_module=specials' );
}
add_filter( 'bwp_gxs_rewrite_rules', 'mxs_add_rules' );

/**
 * Add custom module dir
 * @return string
 */
function mxs_module_dir() {
    return plugin_dir_path( __FILE__ ) . 'modules/';
}
add_filter( 'bwp_gxs_module_dir', 'mxs_module_dir' );
